# Generated by Django 6.1 on 2026-08-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='product',
            name='badge_label',
            field=models.CharField(blank=True, help_text='مثال: پرفروش\u200cترین، جدید، تخفیف ویژه', max_length=50, verbose_name='نشان محصول (Badge)'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('solar', 'تجهیزات خورشیدی'), ('smart-home', 'هوشمندسازی'), ('ai-robotics', 'رباتیک و هوش مصنوعی')], default='solar', max_length=50, verbose_name='دسته\u200cبندی محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='محصول ویژه (کارت بزرگ در صفحه محصولات)'),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
