# Generated by Django 6.1 on 2026-08-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_options_product_badge_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='badge_label',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='badge_label_en',
            field=models.CharField(blank=True, help_text='Example: New, Best Seller, Special Offer', max_length=50, verbose_name='نشان محصول (انگلیسی)'),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_label_fa',
            field=models.CharField(blank=True, help_text='مثال: جدید، پرفروش\u200cترین، تخفیف ویژه', max_length=50, verbose_name='نشان محصول (فارسی)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='توضیحات محصول (انگلیسی)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(default='', verbose_name='توضیحات محصول (فارسی)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام محصول (انگلیسی)'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fa',
            field=models.CharField(default='', max_length=200, verbose_name='نام محصول (فارسی)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='icon',
            field=models.CharField(blank=True, help_text='کلاس آیکون؛ مثال: bi bi-sun', max_length=100, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='برای نمایش محصول در کارت بزرگ\u200cتر گرید Bento فعال کنید.', verbose_name='محصول ویژه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='عدد کمتر، نمایش زودتر در صفحه محصولات.', verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='یک مقدار یکتا، ترجیحاً انگلیسی؛ مثال: smart-solar-inverter', max_length=200, unique=True, verbose_name='لینک (Slug)'),
        ),
    ]
