# Generated by Django 6.1 on 2026-08-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_badge_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientlogo',
            options={'ordering': ['order', '-id'], 'verbose_name': 'لوگوی همکار', 'verbose_name_plural': 'لوگوی'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='محتوا (انگلیسی)'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_fa',
            field=models.TextField(default='', verbose_name='محتوا (فارسی)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, verbose_name='عنوان (انگلیسی)'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fa',
            field=models.CharField(default='', max_length=250, verbose_name='عنوان (فارسی)'),
            preserve_default=False,
        ),
    ]
