# Generated by Django 6.1 on 2026-08-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_clientlogo_options_remove_article_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام برچسب (فارسی)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='نام برچسب (انگلیسی)')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='لینک برچسب (Slug)')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
                'ordering': ['name_fa'],
            },
        ),
        migrations.AlterModelOptions(
            name='clientlogo',
            options={'ordering': ['order', '-id'], 'verbose_name': 'لوگوی همکار', 'verbose_name_plural': 'لوگوهای همکاران'},
        ),
        migrations.AlterField(
            model_name='product',
            name='badge_label_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='نشان محصول (انگلیسی)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='badge_label_fa',
            field=models.CharField(blank=True, max_length=50, verbose_name='نشان محصول (فارسی)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='محصول ویژه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='برچسب\u200cهای مرتبط با این مقاله را انتخاب کنید.', related_name='articles', to='core.tag', verbose_name='برچسب\u200cها'),
        ),
    ]
